metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

processors:
- add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
